# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: image.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bimage.proto\x12\rkornia.protos\"*\n\tImageSize\x12\x0e\n\x06height\x18\x01 \x01(\x05\x12\r\n\x05width\x18\x02 \x01(\x05\"v\n\x05Image\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\x12\x14\n\x0c\x66rame_number\x18\x02 \x01(\x03\x12\x15\n\rencoding_type\x18\x03 \x01(\t\x12,\n\nimage_size\x18\x04 \x01(\x0b\x32\x18.kornia.protos.ImageSizeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'image_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_IMAGESIZE']._serialized_start=30
  _globals['_IMAGESIZE']._serialized_end=72
  _globals['_IMAGE']._serialized_start=74
  _globals['_IMAGE']._serialized_end=192
# @@protoc_insertion_point(module_scope)
